server:
  port: 8084

debug: true

spring:
  application:
    name: web-before-service
  mvc:
    view:
      prefix: /WEB-INF
      suffix: .html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


