server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
#spring:
#  application:
#    name: server_name

management:
  endpoints:
    web:
      exposure:
        include: "*"   #暴露所有的端点我们可以看到更多的服务实例相关信息，
  endpoint:
    health:
      show-details: ALWAYS   #health endpoint是否必须显示全部细节

spring:
  application:
    name: server_name
  boot:
    admin:
      client:
        url: "http://localhost:8788"   #指定SpringBootAdmin服务端地址
        password: user
        username: password
        instance:
          prefer-ip: true
