server:
  port: 8083

debug: true

spring:
  application:
    name: cloud-comsumer
  mvc:
    view:
      prefix: /WEB-INF
      suffix: .jsp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


