server:
  port: 8083

debug: true

spring:
  application:
    name: order-service
  datasource:
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: guoAdmin
    devtools:
      restart:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.guo.Model

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

##开启熔断
#开启熔断
feign:
  hystrix:
    enabled: true





