server:
  port: 8082

debug: true

spring:
  application:
    name: hang_ban_service
  datasource:
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hang?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: guoAdmin
    devtools:
      restart:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.guo.Model


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


